baseURL = "https://et860525.github.io/"
title = 'Mango Blog'
paginate = 5
theme = "PaperMod"

enableInlineShortcodes = true
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
enableEmoji = true
pygmentsUseClasses = true

[languages.en]
languageName = "English"
weight = 1

[languages.en.taxonomies]
category = "categories"
tag = "tags"
series = "series"

[[languages.en.menu.main]]
name = "Home"
url = "/"
weight = 2 

[[languages.en.menu.main]]
name = "Archive"
url = "archives"
weight = 5

[[languages.en.menu.main]]
name = "Search"
url = "search/"
weight = 5

[[languages.en.menu.main]]
name = "Tags"
url = "tags/"
weight = 10

[outputs]
home = [ "HTML", "RSS", "JSON" ]

[params]
env = "production"
author = ["Theme PaperMod", "Mango"]
defaultTheme = "auto"
ShowShareButtons = true
ShowReadingTime = true
displayFullLangName = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowRssButtonInSectionTermList = true
ShowToc = true

[params.homeInfoParams]
Title = "Hello 👋"
Content = """
  Welcome to my blog.
  
  My name is Chen Yu Fan🫠. 
  
      | 📱 Frontend Engineer | 💻 Backend Engineer | 📖 Reader | 
  """

[[params.socialIcons]]
name = "github"
url = "https://github.com/et860525"

[[params.socialIcons]]
name = "linkedin"
url = "https://www.linkedin.com/in/yu-fan-chen-6710b0244"

[[params.socialIcons]]
name = "twitter"
url = "https://twitter.com/Mango9702"

[[params.socialIcons]]
name = "email"
url = "mailto:et860525@gmail.com"

[[params.socialIcons]]
name = "Rss"
url = "index.xml"

[params.assets]
disableHLJS = true
favicon = "/images/favicon/favicon.ico"
favicon16x16 = "/images/favicon/favicon-16x16.png"
favicon32x32 = "/images/favicon/favicon-32x32.png"

[markup.highlight]
codeFences = true
guessSyntax = true
style = "onedark"